name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check node version
        run: node -v
      - name: check yarn version
        run: yarn -v
